### ISSUE TITLE
Please enable my skin for live preview option

### ISSUE THREAD

**Issue by Kenny2github** [jdlrobson/skins.wmflabs.org#3]
I am the owner of [ScratchWikiSkin](https://skins.wmflabs.org/#/skin/scratchwiki2) ([repo](https://github.com/InternationalScratchWiki/ScratchWikiSkin2)) requesting live preview to be enabled.
(Not sure why I'm doing this, but as long as you have it on your site it might as well have a live preview.)

**Comment by jdlrobson** [comment]
Thanks for the request! I've tried enabling this but it throws `( ! ) Deprecated: SkinScratchWikiSkin::setupSkinUserCss must not modify the style module list, this is deprecated since 1.32 [Called from OutputPage::getRlClient in /vagrant/mediawiki/includes/OutputPage.php at line 2996] in /vagrant/mediawiki/includes/debug/MWDebug.php on line 329` in 1.35

Using `initPage` instead of `setupSkinUserCss` is recommended here.

Once that's fixed, I can update this as I'm trying to avoid these errors on my hosted MediaWiki instance.

Is there anyway to change this logo using configuration?:

<img width="651" alt="Screen Shot 2021-01-03 at 10 50 06 AM" src="https://user-images.githubusercontent.com/148752/103486268-7278c680-4db1-11eb-951f-82bdb287555e.png">

**Comment by jdlrobson** [comment]
Enabled on https://skins.wmflabs.org/#/skin/scratchwikiskin2 I'll raise issues for the other customizations.
